#!/bin/bash -e

cp description.md /tmp/description.md
find . -type f -name '*.go' -not -name '*_test.go' | while read line; do
    f=${line##*/}
    n=${f%.*}
    grep -ho 'func\s[A-Z].*{' < $line | \
        sed -e 's/{//g' -e 's/^/    /g' >/tmp/code
    cat << EOF >/tmp/description.sed
/\[\[$n\]\]/ {
    r /tmp/code
    d
}
EOF
    sed -f /tmp/description.sed -i /tmp/description.md
done

echo "Do not edit this file, please edit description.md instead." >> /tmp/description.md
mv /tmp/description.md readme.md

